# Generated by Django 2.2 on 2019-04-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
    ]
